const GLOSS: Record<string, string> = {
  "as ever": "ပုံမှန်အတိုင်း",
  "as usual": "ပုံမှန်အတိုင်း",
  "the same": "အတူတူပင်",
  idea: "စိတ်ကူး",
  vague: "မရှင်းလင်းသော",
  ambiguous: "နှစ်ခွအဓိပ္ပာယ်ရှိသော",
  baby: "ကလေးငယ်",
  "to be amazed": "အံ့ဩသည်",
  "to be shocked": "တုန်လှုပ်သည်",
  accent: "အသံနေအသံထား",
  however: "သို့သော်",
  but: "ဒါပေမဲ့",
  although: "သော်လည်း",
  therefore: "ထို့ကြောင့်",
  besides: "ထို့အပြင်",
  especially: "အထူးသဖြင့်",
  finally: "နောက်ဆုံးတွင်",
  suddenly: "ရုတ်တရက်",
  gradually: "တဖြည်းဖြည်း",
  recently: "မကြာသေးမီက",
  immediately: "ချက်ချင်း",
  approximately: "ခန့်မှန်းခြေ",
  necessary: "လိုအပ်သော",
  possible: "ဖြစ်နိုင်သော",
  impossible: "မဖြစ်နိုင်သော",
  important: "အရေးကြီးသော",
  serious: "ပြင်းထန်သော",
  sufficient: "လုံလောက်သော",
  various: "အမျိုးမျိုးသော",
  similar: "ဆင်တူသော",
  opposite: "ဆန့်ကျင်ဘက်",
  average: "ပျမ်းမျှ",
  majority: "အများစု",
  minority: "လူနည်းစု",
  success: "အောင်မြင်မှု",
  failure: "မအောင်မြင်မှု",
  effort: "ကြိုးစားအားထုတ်မှု",
  research: "သုတေသန",
  result: "ရလဒ်",
  reason: "အကြောင်းရင်း",
  purpose: "ရည်ရွယ်ချက်",
  method: "နည်းလမ်း",
  condition: "အခြေအနေ",
  situation: "အခြေအနေ",
  opportunity: "အခွင့်အရေး",
  responsibility: "တာဝန်",
  experience: "အတွေ့အကြုံ",
  knowledge: "ဗဟုသုတ",
  information: "သတင်းအချက်အလက်",
  conversation: "စကားပြောဆိုမှု",
  opinion: "ထင်မြင်ချက်",
  decision: "ဆုံးဖြတ်ချက်",
  problem: "ပြဿနာ",
  question: "မေးခွန်း",
  answer: "အဖြေ",
  example: "ဥပမာ",
  explanation: "ရှင်းလင်းချက်",
  "to think": "တွေးသည်",
  "to consider": "စဉ်းစားသည်",
  "to decide": "ဆုံးဖြတ်သည်",
  "to continue": "ဆက်လက်လုပ်သည်",
  "to begin": "စတင်သည်",
  "to finish": "ပြီးဆုံးသည်",
  "to increase": "တိုးလာသည်",
  "to decrease": "လျော့ကျသည်",
  "to compare": "နှိုင်းယှဉ်သည်",
  "to explain": "ရှင်းပြသည်",
  "to confirm": "အတည်ပြုသည်",
  "to refuse": "ငြင်းဆိုသည်",
  "to accept": "လက်ခံသည်",
  "to notice": "သတိထားမိသည်",
  "to remember": "မှတ်မိသည်",
  "to forget": "မေ့သည်",
  "to expect": "မျှော်လင့်သည်",
  "to hope": "မျှော်လင့်သည်",
  "to worry": "စိုးရိမ်သည်",
  "to enjoy": "ပျော်ရွှင်သည်",
  "to succeed": "အောင်မြင်သည်",
  "to fail": "မအောင်မြင်",
  "to participate": "ပါဝင်သည်",
  "to apply": "လျှောက်ထားသည်",
  "to graduate": "ဘွဲ့ရသည်",
  company: "ကုမ္ပဏီ",
  office: "ရုံး",
  meeting: "အစည်းအဝေး",
  salary: "လစာ",
  overtime: "အချိန်ပို",
  vacation: "အားလပ်ရက်",
  traffic: "ယာဉ်ကြော",
  station: "ဘူတာ",
  ticket: "လက်မှတ်",
  reservation: "ကြိုတင်စာရင်းသွင်းခြင်း",
  environment: "ပတ်ဝန်းကျင်",
  pollution: "ညစ်ညမ်းမှု",
  nature: "သဘာဝ",
  society: "လူ့အဖွဲ့အစည်း",
  economy: "စီးပွားရေး",
  politics: "နိုင်ငံရေး",
  culture: "ယဉ်ကျေးမှု",
  tradition: "ထုံးတမ်း",
  population: "လူဦးရေ",
  government: "အစိုးရ",
  law: "ဥပဒေ",
  tax: "အခွန်",
  price: "ဈေးနှုန်း",
  quality: "အရည်အသွေး",
  quantity: "ပမာဏ",
  temperature: "အပူချိန်",
  weather: "ရာသီဥတု",
  earthquake: "ငလျင်",
  accident: "မတော်တဆမှု",
  hospital: "ဆေးရုံ",
  medicine: "ဆေး",
  health: "ကျန်းမာရေး",
  diet: "အစားအသောက်",
  exercise: "လေ့ကျင့်ခန်း",
  "to pass": "အောင်သည်",
  "to fail an exam": "ကျသည်",
  examination: "စာမေးပွဲ",
  homework: "အိမ်စာ",
  lecture: "ဟောပြောပွဲ",
  professor: "ပါမောက္ခ",
  student: "ကျောင်းသား",
  classmate: "အတန်းဖော်",
  "to review": "ပြန်လည်သုံးသပ်သည်",
  "to memorize": "အလွတ်ကျက်သည်",
  "to translate": "ဘာသာပြန်သည်",
  translation: "ဘာသာပြန်",
  meaning: "အဓိပ္ပာယ်",
  pronunciation: "အသံထွက်",
  grammar: "သဒ္ဒါ",
  vocabulary: "ဝေါဟာရ",
  kanji: "ခန်ဂျိ",
  sentence: "ဝါကျ",
  paragraph: "စာပိုဒ်",
  article: "ဆောင်းပါး",
  novel: "ဝတ္ထု",
  newspaper: "သတင်းစာ",
  advertisement: "ကြော်ငြာ",
  "to read": "ဖတ်သည်",
  "to write": "ရေးသည်",
  "to listen": "နားထောင်သည်",
  "to speak": "ပြောသည်",
  "to ask": "မေးသည်",
  "to answer": "ဖြေသည်",
  party: "ပါတီ",
  cooperation: "ပူးပေါင်းဆောင်ရွက်မှု",
  general: "အထွေထွေ",
  whole: "တစ်ခုလုံး",
  ward: "ရပ်ကွက်",
  district: "ခရိုင်",
  territory: "နယ်မြေ",
}

export function burmeseGloss(meanings: string[], override?: string) {
  if (override) return override
  for (const meaning of meanings) {
    const direct = GLOSS[meaning.toLowerCase()]
    if (direct) return direct
    const trimmed = meaning.toLowerCase().replace(/\.$/, "")
    if (GLOSS[trimmed]) return GLOSS[trimmed]
  }
  return null
}

export function displayMeaning(meanings: string[], override?: string) {
  return burmeseGloss(meanings, override) ?? meanings[0] ?? ""
}
